import type { Metadata } from "next";
import "./globals.css";
import "aos/dist/aos.css";
import { Open_Sans } from "next/font/google";
import NavbarScrollEffect from "@/components/NavbarScrollEffect";
import Footer from "@/components/Footer";
import AOSInitializer from "@/components/AOSInitializer";
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: [
    "300", // Light
    "400", // Regular
    "500", // Medium
    "600", // Semi-bold
    "700", // Bold
    "800", // Extra-bold
  ],
  // variable: "--font-open-sans",
});
export const metadata: Metadata = {
  title: "TOURS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={openSans.className}>
      <body>
        <AOSInitializer />
        <NavbarScrollEffect />
        {children}
        <Footer />
      </body>
    </html>
  );
}
